# This rule is not used by the project node-operation-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the nodeops.k8s.preferred.jp.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: node-operation-controller
    app.kubernetes.io/managed-by: kustomize
  name: noderemediation-editor-role
rules:
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - noderemediations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - noderemediations/status
  verbs:
  - get
